#!/usr/bin/env python3
"""
Build .env from .env.example plus optional local overrides file (if you create one) + compose Airflow URLs.
Run from project root: python3 scripts/merge_local_env.py
Does not print secret values.
"""
from __future__ import annotations

from pathlib import Path


def parse_env_file(path: Path) -> dict[str, str]:
    out: dict[str, str] = {}
    if not path.exists():
        return out
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, val = line.partition("=")
        key = key.strip()
        val = val.strip().strip('"').strip("'")
        if key:
            out[key] = val
    return out


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    example = root / ".env.example"
    target = root / ".env"

    data = parse_env_file(example)
    for extra in (root / "local.env", root / "ATT52840.env"):
        data.update(parse_env_file(extra))

    # Airflow DB/Redis: use compose service hostnames on the Docker network
    data["AIRFLOW__DATABASE__SQL_ALCHEMY_CONN"] = (
        "postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow"
    )
    data["AIRFLOW__CELERY__RESULT_BACKEND"] = (
        "db+postgresql://airflow:airflow@airflow-postgres:5432/airflow"
    )
    data["AIRFLOW__CELERY__BROKER_URL"] = "redis://redis:6379/0"
    data.setdefault("AIRFLOW_UID", "50000")
    data.setdefault("AIRFLOW_IMAGE_NAME", "tariff-audit-airflow:3.1.7")
    data.setdefault("POSTGRES_USER", "airflow")
    data.setdefault("POSTGRES_PASSWORD", "airflow")
    data.setdefault("POSTGRES_DB", "airflow")

    db_type = data.get("DB_TYPE", "sqlite")
    if db_type == "postgres":
        missing = [k for k in ("DB_USER", "DB_PASSWORD", "DB_HOST", "DB_PORT", "DB_NAME") if not data.get(k)]
        if missing:
            raise SystemExit(
                f"DB_TYPE=postgres but these vars are missing or empty: {', '.join(missing)}. "
                "Add them to local.env (gitignored) or .env.example."
            )

    # Stable key order: app DB first, then Airflow
    preferred = [
        "DB_TYPE",
        "DB_PATH",
        "DB_HOST",
        "DB_PORT",
        "DB_NAME",
        "DB_USER",
        "DB_PASSWORD",
        "TESSERACT_PATH",
        "TESSDATA_PREFIX",
        "OPENAI_API_KEY",
        "ENV_FILE_PATH",
        "AIRFLOW_PROJ_DIR",
        "AIRFLOW_UID",
        "AIRFLOW_IMAGE_NAME",
        "AIRFLOW__CORE__FERNET_KEY",
        "AIRFLOW__API__SECRET_KEY",
        "AIRFLOW__API_AUTH__JWT_SECRET",
        "AIRFLOW__DATABASE__SQL_ALCHEMY_CONN",
        "AIRFLOW__CELERY__RESULT_BACKEND",
        "AIRFLOW__CELERY__BROKER_URL",
        "POSTGRES_USER",
        "POSTGRES_PASSWORD",
        "POSTGRES_DB",
        "_AIRFLOW_WWW_USER_USERNAME",
        "_AIRFLOW_WWW_USER_PASSWORD",
    ]
    seen = set()
    lines: list[str] = [
        "# Generated by scripts/merge_local_env.py — do not commit. Regenerate after editing .env.example or local.env.",
        "",
    ]
    for k in preferred:
        if k in data:
            lines.append(f"{k}={data[k]}")
            seen.add(k)
    for k in sorted(data.keys()):
        if k not in seen:
            lines.append(f"{k}={data[k]}")
    lines.append("")

    target.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {target} ({len(data)} variables).")


if __name__ == "__main__":
    main()
